### ISSUE TITLE
阴阳师的美术更新改变了组队界面的布局

### ISSUE THREAD

**Issue by y0umu** [luoy2/pyOnmyoji#13]
如题，某一次（三周年）神秘更新后阴阳师的组队界面的布局发生了变化，最重要的一条就是组队界面的开始战斗按钮的坐标发生了变化。`party.py`和`party_member.py`里引用的仍然是旧的组队用户界面的[StartFight](https://github.com/luoy2/pyOnmyoji/blob/7c7c89adff8c6d19dc8d7011219f4e1ce01ddc07/colors/util.py#L61)的颜色和坐标，所以不做相应更新的话是没办法点击开始按钮的。

类似的问题同样出现在其他有界面布局变动的地方，如业原火挑战。

你问我为什么不自己把这些改过来然后pull request？~~因为好不容易放个假赶紧多做做活动啊谁要去debug~~

~~好吧不就是改个坐标吗我找个时间测量一下~~

**Comment by y0umu** [comment]
我试着用colorPicker找了新的坐标，然而并没有用，果然还需要调试……

**Comment by luoy2** [comment]
应该没这么难调试，小伙子加油

Thank you!
Sincerely,
Yikang Luo


在 2020年1月30日，下午9:05，y0umu <notifications@github.com> 写道：

﻿

我试着用colorPicker找了新的坐标，然而并没有用，果然还需要调试……
