### ISSUE TITLE
No more official PC version, fareware pyOnmyoji

### ISSUE THREAD

**Issue by y0umu** [luoy2/pyOnmyoji#20]
As in the topic, the [official site of Onmyoji](https://yys.163.com/) no longer provides a genuine desktop version. Although there are still (possibly deprecated) binary installers available at sites like the NGA forum, I read it as a clear sign that we should say fareware to this lovely project.

**Comment by luoy2** [comment]
cheers mate！

Thank you!
Sincerely,
Yikang


在 2022年2月9日，下午10:08，y0umu ***@***.***> 写道：

﻿

As in the topic, the official site of Onmyoji<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fyys.163.com%2F&data=04%7C01%7C%7Ca4ad528ca58d46978fcc08d9ebd5978f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637800124876378215%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ROsYUI9zs8GV3zERYbVpOw20%2BkD%2F%2Fm6NjkGQZqH%2B%2BY0%3D&reserved=0> no longer provides a genuine desktop version. Although there are still (possibly deprecated) binary installers available at sites like the NGA forum, I read it as a clear sign that we should say fareware to this lovely project.

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fluoy2%2FpyOnmyoji%2Fissues%2F20&data=04%7C01%7C%7Ca4ad528ca58d46978fcc08d9ebd5978f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637800124876378215%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=nv5H3T4of5aBpEHm4cNb%2BkkMz%2B4JAk5PgpLbeKB0Bhc%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAE5LWOS7Z76DUDMWD5TKEELU2JYMJANCNFSM5N5TGZ5Q&data=04%7C01%7C%7Ca4ad528ca58d46978fcc08d9ebd5978f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637800124876378215%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HLZBspXEdJ3AxEShEzEwy5aq4fOTL9jMt5plU9OpUOM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ca4ad528ca58d46978fcc08d9ebd5978f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637800124876378215%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=D99MiS%2Fpy4RIUIjy%2FRrdENFygqO8xyuPHKFB8ltQK0Q%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ca4ad528ca58d46978fcc08d9ebd5978f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637800124876378215%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=UKWM2V1tMcU%2B6tRWvyuJRrSaGUHXmLnlzXdLNR%2BV7eg%3D&reserved=0>.
