### ISSUE TITLE
如何启动由登录器开启的游戏子窗口呢？

### ISSUE THREAD

**Issue by tianyu150** [luoy2/pyOnmyoji#22]
如何启动由登录器开启的游戏子窗口呢？

**Comment by y0umu** [comment]
正如 issue #20 所提到的，如果您是从[官方网站](https://yys.163.com/)下载的模拟器版，那么很遗憾这个 repo 的代码都不会工作。

很久以前，官方提供的桌面版是某种“电子包”或者某种基于chromium的包，无论如何，它有一个真正的 x86 可执行文件 `onmyoji.exe`。这个 repo 的故事就是从这个 `onmyoji.exe` 展开的。

如果你有兴趣，可以尝试在互联网上搜索一下别人存的官方老版桌面版下载地址。比如NGA论坛上的[这一帖](https://ngabbs.com/read.php?tid=29661629)。 **我没有尝试过这种方法，我也AFK很久了。使用非官方途径获得的旧版安装包（哪怕它来自真正的官方服务器）是否本身会造成封号、限制玩法，本人不知情。如果你一定要试，责任自负**

**Comment by y0umu** [comment]
旁边一提，我魔改过刷御魂的代码（既没有合并到本 repo 也没有提交到我自己的fork），仅用了6小时不到。第二天登录就被限制玩法7天了。网易的反作弊多少是有点意思的。看过一个访谈，他们也在训练 AI 识别作弊（虽然数据上有多强我就不得而知了）。

旁边一提的旁边一提，这 repo 的大部分程序逻辑在大部分模拟点击硬编码的坐标生效之前会加一个随机偏移。这看起来似乎是在糊弄反作弊机制。然而，我请读者思考这个问题：给你一堆二维坐标，告诉你他们都落在某个**线性方程**附近，请你近似这个方程，你会怎么做？ 现在再给你一堆二维坐标，告诉你它们都是围绕某个**固定点**的，请你近似这个点，你会怎么做？

（我的话，也许直接暴力上最小二乘法和K-means了吧，读者应该会有更好的想法）

你算出这个线这个点之后，服务器给你回传了一堆新的玩家行为数据，你会怎么做？

你在御魂通过的奖励结算画面设置了一些微妙的掉帧/迟滞/提前/偏移……，你发现有的玩家玩到一半加成都没关，卡在结算页面，却还在屏幕上点点这点点那，就是不退出来，你会怎么做？

**Comment by y0umu** [comment]
说正点的，如果你确实想知道在 good old days 我们怎么使用这 repo 的代码，以下是一些提示。

0. 这 repo 根目录中的 py 程序，有的编写是程序运作需要的逻辑，如`combat.py` 和 `controller.py`，有的是面向用户的“脚本”，如`main.py`、`party.py` 和 `baiguiyexing.py` 。[README.md](https://github.com/luoy2/pyOnmyoji/blob/master/README.md) 已经暗示或者明示了你哪些是面向用户的脚本。

1. 脚本是以来窗口名称寻找阴阳师游戏窗口的。遗憾的是原作者并没有告诉你他也是个[Sandboxie](https://sandboxie-plus.com/)爱好者，并且他用 sandboxie 运行阴阳师。Sandboxie ，在默认的设置下，会向其中运行的应用程序的窗口名称左右添加`[#]`，这大概解释了为什么有的脚本用这个代码初始化目标窗口名称
```python
constants.init_constants(u'[#] 阴阳师-网易游戏 [#]', move_window=False)
```

如果你不用 sandboxie，你应该把它改成
```python
constants.init_constants(u'阴阳师-网易游戏', move_window=False)
```
