### ISSUE TITLE
Resource missing

### ISSUE THREAD

**Issue by AlexLJC** [luoy2/pyOnmyoji#5]
MAIN_TUPO = ['res/jiejietupo/main.png', (0, 0, 1700, 200)]
ATTACK = ['res/jiejietupo/attack.png', (0, 0, 1720, 1010)]

class SINGLE_TARGET:
    FINISHED = 'res/jiejietupo/finished.png'
    FAILED = 'res/jiejietupo/failed.png'
    METAL = 'res/jiejietupo/metal.png'
    FINISHED_METAL = 'res/jiejietupo/finished_metal.png'

class PARTY_CORDS(enum.Enum):
    YAOQIFENGYIN = (345, 839)

**Comment by luoy2** [comment]
Those png files were used by old module taken screenshots. It is really unstable. The new module is finding color cords not png. Will upload a tutorial in the future.

Thank you!
Sincerely,
Yikang Luo


On Oct 11, 2018, at 1:43 AM, AlexLJC <notifications@github.com<mailto:notifications@github.com>> wrote:


MAIN_TUPO = ['res/jiejietupo/main.png', (0, 0, 1700, 200)]
ATTACK = ['res/jiejietupo/attack.png', (0, 0, 1720, 1010)]

class SINGLE_TARGET:
FINISHED = 'res/jiejietupo/finished.png'
FAILED = 'res/jiejietupo/failed.png'
METAL = 'res/jiejietupo/metal.png'
FINISHED_METAL = 'res/jiejietupo/finished_metal.png'

class PARTY_CORDS(enum.Enum):
YAOQIFENGYIN = (345, 839)
