### ISSUE TITLE
Dependency 'keyboard' causing problems for Python 3.7 on Windows 10 (x64)

### ISSUE THREAD

**Issue by y0umu** [luoy2/pyOnmyoji#6]
Hi there,

Although it might be OK with Python 3.6, I can confirm using keyboard==0.13.2 specified in colorPicker/requirements.txt with Python 3.7 on Windows 10 (x64) will [throw Overflowerror](https://github.com/boppreh/keyboard/issues/186) when I run `colorPicker/main.py`. Workarounds are available in [that very discussion](https://github.com/boppreh/keyboard/issues/186#issuecomment-460635871).

Maybe you want to warn py37 users about it in README.md?

**Comment by luoy2** [comment]
Updated read me.
