### ISSUE TITLE
我想问一下colorPicker的使用方法。

### ISSUE THREAD

**Issue by Rambox1** [luoy2/pyOnmyoji#8]
是需要把colors/util.py里的常量都给改掉吗，求具体的操作步骤

**Comment by luoy2** [comment]
Inside the folder colorpicker, there is a pyqt tool you can just run to pick color; and you need to read through the code to decide which color you should change the coordinates; currently I am too busy to form a clean instruction on how should people implement stuff, but I suggest you look at the jiejietupo.py as for an example.

Let me know,
Yk

**Comment by kraviszhong** [comment]
有时间出一个1080P的包么，还在尝试中

**Comment by y0umu** [comment]
> 
> 
> 是需要把colors/util.py里的常量都给改掉吗，求具体的操作步骤

我根据源码写了一个colorPicker的README，现在在pull request里面，你不妨看下（顺便检查一下有没有哪里不对）。

**Comment by luoy2** [comment]
merged.
