### ISSUE TITLE
脚本支持版本

### ISSUE THREAD

**Issue by deng-ming-hao** [luoy2/pyOnmyoji#9]
大佬，你这个支持的是pc版吗

**Comment by luoy2** [comment]
对啊， 但是许久没维护了； 你得自己去找像素点

________________________________
发件人: D <notifications@github.com>
发送时间: Friday, June 28, 2019 10:55:49 AM
收件人: luoy2/pyOnmyoji
抄送: Subscribed
主题: [luoy2/pyOnmyoji] 脚本支持版本 (#9)


大佬，你这个支持的是pc版吗

―

**Comment by deng-ming-hao** [comment]
哦哦，谢谢大佬


| |
deng.minghao
|
|
runnerd@163.com
|
签名由网易邮箱大师定制
在2019年6月28日 10:56，YikangLuo<notifications@github.com> 写道：
对啊， 但是许久没维护了； 你得自己去找像素点

________________________________
发件人: D <notifications@github.com>
发送时间: Friday, June 28, 2019 10:55:49 AM
收件人: luoy2/pyOnmyoji
抄送: Subscribed
主题: [luoy2/pyOnmyoji] 脚本支持版本 (#9)


大佬，你这个支持的是pc版吗

―
